main_task:
  container:
    image: rust:latest
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cargo update && cat Cargo.lock
  build_script: cargo build
  alloc_script: cargo build --features="alloc"
  alloc_compat_script: cargo build --features="alloc compat"
  std_script: cargo build --features="std"
  std_compat_script: cargo build --features="std compat"

compat_task:
  container:
    image: rust:1.34.2-stretch
  build_script: cargo build --features="compat"
  alloc_script: cargo build --features="alloc compat"
  std_script: cargo build --features="std compat"

nightly_task:
  container:
    image: rustlang/rust:nightly
  build_script: cargo build --features="alloc std"
  script: cargo doc --no-deps --document-private-items --all-features
